version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: school_crm
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_TOKEN=8550457735:AAHznV8NMMTjlVL_m532JK51nQ7VLtMBBRI
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: