FROM node:18-alpine

WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./
RUN npm install --production

# Copiar el resto del código
COPY . .

# Exponer puerto de la API
EXPOSE 3000

# Comando para iniciar el servidor
CMD ["npm", "run", "dev"]