# Generated by Django 5.2.10 on 2026-01-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_chat', models.CharField(default='INICIO', max_length=50)),
                ('carrera_interes', models.CharField(blank=True, max_length=100, null=True)),
                ('cita_fecha', models.CharField(blank=True, max_length=100, null=True)),
                ('asesor_asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
