# Generated by Django 5.2.12 on 2026-03-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='telegram_id',
            field=models.CharField(max_length=100),
        ),
    ]
